### PR TITLE
Release new 1.0.13 version

### PR DESCRIPTION
**Pull request by Gitsaibot**
-Request permissions at runtime on Android 6 upwards.
-Support display lunar/festival when Language is Chinese.
-Update translations.
-Minor Layout fixes.
-Lots of bug fixes.

### CODE REVIEW

**Comment by jspricke** [comment]
Thanks! What about directly reorganizing it as discussed in #270? Would be great to have it in the release. I can help with it as well.

**Comment by jspricke** [comment]
fdroidclient is a nice example:

https://gitlab.com/fdroid/fdroidclient/tree/master/metadata

You can move the screenshots, feature images and changelogs, as far as I 
understand. I would propose to leave the rest at the current place for 
now. Thanks for working on this!

**Comment by jspricke** [comment]
Three files seems to be correct. What do you mean by publish dictionary?

**Comment by jspricke** [comment]
Hey, I pushed some commits here to clean it up. Hope you like it :).

**Comment by xsoh** [comment]
Great job!
Also no need for `publish` directory while `metadata` is exist 👍

**Pull request merged**
