### PR TITLE
Fix #641

### LINKED ISSUE #641: Crash when opening settings [new in 1.0.20]
Etar app crashes after clicking on **settings** in sidebar.
Crash started happening after recent update to 11.0.20

## Device
_Device:_ Nokia 7+
_Android_: 9
_Etar-Version_: 11.0.20 (F-droid)
_Permissions:_ Calendar, Contacts, Storage

Additionally, I'm using [Offline Calendar](https://f-droid.org/en/packages/org.sufficientlysecure.localcalendar/) for local calendars.

## Crash Log
[etar_crash.txt](https://github.com/Etar-Group/Etar-Calendar/files/4144262/etar_crash.txt)

```
02-02 15:06:43.428  2563  2563 D StatusBar: hiding the MENU button
02-02 15:06:43.429  1465  1889 I ActivityManager: Displayed ws.xsoh.etar/com.android.calendar.settings.SettingsActivity: +125ms
02-02 15:06:43.431  5103  7745 D ContentProvider: checkPermissionAndAppOp, ws.xsoh.etar want to check android.permission.READ_CALENDAR(8) was skipped. 8/9
02-02 15:06:43.434  1465  2425 D WifiTrafficPoller: TRAFFIC_STATS_POLL true Token 19 num clients 1
02-02 15:06:43.435  1465  2425 D WifiTrafficPoller:  packet count Tx=1564 Rx=1642
02-02 15:06:43.444   795   943 D SDM     : DisplayBase::BuildLayerStackStats: LayerStack layer_count: 6, app_layer_count: 5, gpu_target_index: 5, display type: 0
02-02 15:06:43.454  9322  9322 E AndroidRuntime: FATAL EXCEPTION: main
02-02 15:06:43.454  9322  9322 E AndroidRuntime: Process: ws.xsoh.etar, PID: 9322
02-02 15:06:43.454  9322  9322 E AndroidRuntime: java.lang.IllegalStateException: name must not be null
02-02 15:06:43.454  9322  9322 E AndroidRuntime: 	at com.android.calendar.persistence.CalendarRepository$CalendarLiveData.getContentProviderValue(CalendarRepository.kt:73)
02-02 15:06:43.454  9322  9322 E AndroidRuntime: 	at com.android.calendar.persistence.CalendarRepository$CalendarLiveData.getContentProviderValue(CalendarRepository.kt:55)
02-02 15:06:43.454  9322  9322 E AndroidRuntime: 	at com.android.calendar.persistence.ContentProviderLiveData$getContentProviderValueAsync$1$accounts$1.invokeSuspend(ContentProviderLiveData.kt:60)
02-02 15:06:43.454  9322  9322 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
02-02 15:06:43.454  9322  9322 E AndroidRuntime: 	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:233)
02-02 15:06:43.454  9322  9322 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:874)
02-02 15:06:43.454  9322  9322 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:100)
02-02 15:06:43.454  9322  9322 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:198)
02-02 15:06:43.454  9322  9322 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6729)
02-02 15:06:43.454  9322  9322 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
02-02 15:06:43.454  9322  9322 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
02-02 15:06:43.454  9322  9322 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
02-02 15:06:43.457  1465  8535 W ActivityManager:   Force finishing activity ws.xsoh.etar/com.android.calendar.settings.SettingsActivity
02-02 15:06:43.458  1465  8535 D ActivityTrigger: ActivityTrigger activityPauseTrigger 
02-02 15:06:43.459  1004  1181 W statsd  : not interested in atom 130601
02-02 15:06:43.460   795   943 D SDM     : DisplayBase::BuildLayerStackStats: LayerStack layer_count: 6, app_layer_count: 5, gpu_target_index: 5, display type: 0
02-02 15:06:43.460  1465  1819 D StatusBarManagerService: manageDisableList userId=0 what=0x0 pkg=Window{16397ef u0 ws.xsoh.etar/com.android.calendar.settings.SettingsActivity}
02-02 15:06:43.460  1465  1819 D StatusBarManagerService: disableLocked net1 = 0; net2 = 0 pkg=Window{16397ef u0 ws.xsoh.etar/com.android.calendar.settings.SettingsActivity}
02-02 15:06:43.461  2563  2563 D StatusBar: hiding the MENU button
02-02 15:06:43.462  1465  8535 W ActivityManager:   Force finishing activity ws.xsoh.etar/com.android.calendar.AllInOneActivity
```

### PR DESCRIPTION
**Pull request by dschuermann**
Allow name and displayName to be null.
Looks like there could be calendars with a null internal name.

### CODE REVIEW

**Comment by jspricke** [comment]
What will be shown if the name is null?

**Comment by dschuermann** [comment]
Screenshot_20200203-200223

**Comment by dschuermann** [comment]
Still everything works as expected.
The reported issue happens when the ``name`` is null. This is only the internal name, such as "https://nextcloud.example.com/remote.php/dav/calendars/..." in case of davx5.

**Comment by jspricke** [comment]
Can you add a "unnamed" or something instead of the empty string?

**Comment by dschuermann** [comment]
Hm, sure: https://github.com/Etar-Group/Etar-Calendar/pull/647

**Comment by dschuermann** [comment]
Lol, my test calendar with a null ``name`` and null ``displayName`` broke the Google Calendar, i.e., it shows no calendars and no events.
So we are now officially better in this regard ;)

Screenshot_20200205-100231

**Pull request merged**
