### PR TITLE
Fix crash when saving events that have a custom color (issue #248).

### PR DESCRIPTION
**Pull request by victorfernandezfilewave**

### CODE REVIEW

**Comment by victorfernandezfilewave** [comment]
The first commit fixed setting the color by tapping the palette icon when viewing an event. This second commit now fixes the crash as well when setting it in the event editor activity (e.g. when creating a new event or when editing it).

**Comment by bertalanp99** [comment]
This issue still persists for me

`FATAL EXCEPTION: IntentService[AsyncQueryServiceHelper]
Process: ws.xsoh.etar, PID: 8405
java.lang.IllegalArgumentException: Color type: 1 and index 0 does not exist for account.
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:165)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
	at android.content.ContentProviderProxy.update(ContentProviderNative.java:568)
	at android.content.ContentResolver.update(ContentResolver.java:1412)
	at com.android.calendar.AsyncQueryServiceHelper.onHandleIntent(AsyncQueryServiceHelper.java:208)
	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:68)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.os.HandlerThread.run(HandlerThread.java:61)`

**Comment by bertalanp99** [comment]
I am using `v1.0.13`

Steps to reproduce:
1. Use DAVdroid to sync with a DalDAV server (Radicale)
2. Enable event colours in DAVdroid
3. In Etar, try changing an event's colour, either by opening it and tapping the palette icon, or tapping the edit icon and then the palette and saving (or taping 'back')

**Comment by bertalanp99** [comment]
Oh, stupid me. When will `v1.0.14` be available on F-Droid? I managed to build on my PC and transfer the debug apk to my phone and now it works (although the About option still shows `v1.0.13` for some reason)

**Pull request merged**
