### PR TITLE
improved metadata and screenshots

### PR DESCRIPTION
**Pull request by PanderMusubi**

### CODE REVIEW

**Comment by jspricke** [comment]
AFAIK F-Droid doesn't delete old files, so I would propose to override the old file names.

**Comment by PanderMusubi** [comment]
I think they do. @Izzy ?

**Comment by IzzySoft** [comment]
@PanderMusubi no idea if that bug is already fixed. Please check with the fdroidserver issue tracker, I currently lack the time.

**Comment by PanderMusubi** [comment]
@jspricke screenshots phone are now complete

**Comment by jspricke** [comment]
Did you check the fdroidserver issue tracker?

**Comment by PanderMusubi** [comment]
Could not find it. Perhaps @IzzySoft can point is the right direction.

**Comment by jspricke** [comment]
https://gitlab.com/fdroid/fdroidserver/-/issues/490

**Comment by IzzySoft** [comment]
I recently noticed offering a decent bounty helps getting such issues fixed within a week… :speak_no_evil:

<sup>not asking that for me – not my area of procifiency, so I cannot fix that. But I'm available as "mediator" to be trusted with the funds until the dev accepting the bounty has delivered, if wanted</sup>

**Comment by PanderMusubi** [comment]
Can you merge this as all required screenshots have been committed

**Comment by jspricke** [comment]
The F-Droid server issue has not been fixed and you still delete files, so no.

**Comment by jspricke** [comment]
Merged in #680, thanks!

**Pull request closed without merging**
