### PR TITLE
Fixed issue with wrong height of events in week view

### PR DESCRIPTION
**Pull request by 0xym**
I'm not sure what about event_min_height dimension - should we keep it, or should we use a real minimum height instead.

### CODE REVIEW

**Comment by 0xym** [comment]
Fixes #431

**Comment by 0xym** [comment]
As far as I know "dip" is not scalable, so using it won't solve the issue in the long run. Also padding is not scaling with the font size, so "sp" won't produce the right values for all cases.

**Comment by jspricke** [comment]
Some events are shown too small now even though there is enough space. Can you have a look?
Screenshot_20190906-104247_Etar
Screenshot_20190906-104313_Etar

**Comment by jspricke** [comment]
It seems to only happen upon first start (after installing Etar). Restarting make the event big enough to read the description. The event is only 10 minutes long, could be related.

**Comment by jspricke** [comment]
Played around a little:
* It's broken upon every app start (not only after installing Etar).
* Setting MIN_EVENT_HEIGHT the old way but in init() results in the same broken behavior. -> So we need to set it early.
* Computing fontHeight for the first time gives a really small value (17.0 compared to 66.0 for MIN_EVENT_HEIGHT) -> I guess we have a race condition.

This worked for me, not sure if it makes sense:
```
        float event_min_height = mResources.getDimension(R.dimen.event_min_height);
        if(fontHeight < event_min_height) {
            fontHeight = event_min_height;
        }
```

**Comment by 0xym** [comment]
I have looked into it and the were two issues:
mAnimateDayEventHeight was set to MIN_UNEXPANDED_ALLDAY_EVENT_HEIGHT, before MIN_UNEXPANDED_ALLDAY_EVENT_HEIGHT was initialized to the right value (but error didn't have any immediate adverse effect).
The culprit here was 
`        mEventGeometry.setMinEventHeight(MIN_EVENT_HEIGHT);
`
This line was called before the right value of MIN_EVENT_HEIGHT was set and it resulted in the observed issue.
I've found out that font is not used prior to init so I have moved it to the constructor - after all required values are computed.

**Comment by jspricke** [comment]
Thanks, that looks much better :). I pushed away some unrelated whitespace changes and will test it the next days and merge then.

**Pull request merged**
