### PR TITLE
Updated fr (French) translation

### PR DESCRIPTION
**Pull request by mquinson**
Commit made via Stringlate

### CODE REVIEW

**Comment by jspricke** [comment]
Hi, thanks for the pull request and sorry for keep you waiting. You patch changes quite a lot, could you maybe clean it up, so only the relevant parts are changed? That would make it easier to review it. Thanks!

**Comment by mquinson** [comment]
Hello, sorry for the mess. I did this commit with stringlate, which is a nice little application for the projects not having a specific procedure for translation, but messy for others.

Could you point me to the page describing how I should update the translation in a proper way, please? In the meanwhile, I agree with you: you should even close this PR. I'll do another one.

**Comment by jspricke** [comment]
No need to close it, just push (or force push) into this branch ;). I've normally edited the files with an editor, not sure if there is documentation on how to do it properly.

**Comment by mquinson** [comment]
I seem to fail to find the time to do so. I don't want this half backed PR to block other potential contributors. I prefer to close it, as I'd have to redo the translation completely with the proper tools. Don't worry, that was not such a huge work either.

Sorry for the noise.

**Pull request closed without merging**
